services:
  - type: web
    name: studyhive-backend
    env: node
    rootDir: backend
    buildCommand: npm install --legacy-peer-deps
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URI
        value: "mongodb+srv://temesgenbekalu74_db_user:FI07LxFXSlImrnwq@cluster1.mj83gys.mongodb.net/studyhive?retryWrites=true&w=majority&appName=Cluster1"
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
